- name : Create volume folder for mysql
  become: true
  file:
    path: '{{volume_path}}'
    state: directory


- name : Delete old containers
  become: true
  docker_container:
    name: '{{container_name}}'
    state: absent
    force_kill: yes


- name : Delete old images if exists
  become: true
  docker_image:
    name: '{{image_name}}'
    state: absent
    force_absent: yes



- name: Run mysql container
  become: true
  docker_container:
    name: '{{db_host}}'
    image: '{{image_name}}'
    networks:
      - name: '{{docker_network_name}}'
    env:
      MYSQL_USER: '{{db_user}}'
      MYSQL_DATABASE: '{{db_name}}'
      MYSQL_PASSWORD: '{{db_pass}}'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - '{{volume_path}}/:/var/lib/mysql/'
    restart_policy: always