
- name : run container
  become: true
  docker_container:
    name: '{{container_name}}'
    image: '{{image_name}}'
    state: started
    networks:
      - name: '{{docker_network_name}}'
    published_ports:
      - 443:443
      - 80:80
    detach: yes
    restart_policy: always



    