
- name : run container
  become: true
  docker_container:
    name: '{{container_name}}'
    image: '{{image_name}}'
    state: started
    networks:
      - name: '{{docker_network_name}}'
    published_ports:
      - 443:443
    detach: yes
    auto_remove: yes
    pull: no


- name: test
  command: echo "123"
    